package rpc

import (
	"fmt"
	"log"
	"math"
	"net"
	"regexp"
	"strconv"
	"strings"

	"github.com/nezhahq/nezha/model"
	"github.com/nezhahq/nezha/service/singleton"
)

var corePattern = regexp.MustCompile(`(?i)(\d+)\s+(?:[a-z]+\s+)?core\b`)
var generatedNamePattern = regexp.MustCompile(`^(?:[A-Z]{2}-)?\d+C\d+G(?:-[A-Z0-9]+)?$`)

func maybeUpdateDefaultServerName(server *model.Server) bool {
	if server == nil {
		fmt.Println("[server-name][skip] server is nil")
		return false
	}

	existingName := strings.TrimSpace(server.Name)
	existingIsGenerated := isAutoGeneratedName(existingName)

	if existingName != "" && !existingIsGenerated {
		fmt.Printf("[server-name][skip] id=%d existing-name=%q manual=true\n", server.ID, existingName)
		return false
	}

	if server.GeoIP != nil {
		fmt.Printf("[server-name][input] id=%d country=%q ipv4=%q ipv6=%q geo=%+v\n",
			server.ID,
			server.GeoIP.CountryCode,
			server.GeoIP.IP.IPv4Addr,
			server.GeoIP.IP.IPv6Addr,
			server.GeoIP)
	} else {
		fmt.Printf("[server-name][input] id=%d geoip=nil\n", server.ID)
	}
	if server.Host != nil {
		fmt.Printf("[server-name][host] id=%d mem=%d cpu=%v\n", server.ID, server.Host.MemTotal, server.Host.CPU)
	} else {
		fmt.Printf("[server-name][host] id=%d host=nil\n", server.ID)
	}

	name, hasGeoInfo, ok := generateFeatureBasedServerName(server)
	if !ok {
		fmt.Printf("[server-name][generate][fail] id=%d geo=%+v host=%+v\n", server.ID, server.GeoIP, server.Host)
		return false
	}
	fmt.Printf("[server-name][generate][success] id=%d name=%q\n", server.ID, name)

	if existingName == name {
		fmt.Printf("[server-name][generate][unchanged] id=%d name=%q\n", server.ID, name)
		return false
	}

	if existingName != "" && !hasGeoInfo {
		fmt.Printf("[server-name][generate][skip-no-new-info] id=%d existing=%q candidate=%q\n", server.ID, existingName, name)
		return false
	}

	query := singleton.DB.Model(&model.Server{}).Where("id = ?", server.ID)
	if existingName == "" {
		query = query.Where("name = '' OR name IS NULL")
	} else {
		query = query.Where("name = ?", existingName)
	}
	result := query.Update("name", name)

	if result.Error != nil {
		log.Printf("NEZHA>> failed to persist auto-generated server name for %d: %v", server.ID, result.Error)
		return false
	}

	if result.RowsAffected == 0 {
		return false
	}

	server.Name = name
	return true
}

func generateFeatureBasedServerName(server *model.Server) (string, bool, bool) {

	if server == nil || server.Host == nil || server.GeoIP == nil {
		fmt.Printf("[server-name][generate] missing data id=%d host=%v geo=%v\n",
			func() uint64 {
				if server != nil {
					return server.ID
				}
				return 0
			}(),
			server != nil && server.Host != nil,
			server != nil && server.GeoIP != nil)
		return "", false, false
	}

	country := strings.ToUpper(strings.TrimSpace(server.GeoIP.CountryCode))
	hasCountry := len(country) == 2 && country != "XX"
	fmt.Printf("[server-name][generate] id=%d raw-country=%q final-country=%q has-country=%t\n", server.ID, server.GeoIP.CountryCode, country, hasCountry)

	cpuCores := calculateCPUCores(server.Host.CPU)
	if cpuCores == 0 {
		fmt.Printf("[server-name][generate] id=%d cpu-info=%v -> cores=0\n", server.ID, server.Host.CPU)
		return "", false, false
	}
	fmt.Printf("[server-name][generate] id=%d cpu-cores=%d\n", server.ID, cpuCores)

	memGB := calculateMemoryInGB(server.Host.MemTotal)
	if memGB == 0 {
		fmt.Printf("[server-name][generate] id=%d mem-bytes=%d -> memGB=0\n", server.ID, server.Host.MemTotal)
		return "", false, false
	}
	fmt.Printf("[server-name][generate] id=%d mem-bytes=%d memGB=%d\n", server.ID, server.Host.MemTotal, memGB)

	ipSegment := extractIPSegment(server.GeoIP.IP)
	fmt.Printf("[server-name][generate] id=%d ipv4=%q ipv6=%q joined=%q segment=%q\n",
		server.ID,
		server.GeoIP.IP.IPv4Addr,
		server.GeoIP.IP.IPv6Addr,
		server.GeoIP.IP.Join(),
		ipSegment)

	var parts []string
	hasGeoInfo := false

	if hasCountry {
		parts = append(parts, country)
		hasGeoInfo = true
	}

	parts = append(parts, fmt.Sprintf("%dC%dG", cpuCores, memGB))

	if ipSegment != "" {
		parts = append(parts, ipSegment)
		hasGeoInfo = true
	}

	name := strings.Join(parts, "-")

	return name, hasGeoInfo, true
}

func isAutoGeneratedName(name string) bool {
	if name == "" {
		return true
	}
	return generatedNamePattern.MatchString(strings.ToUpper(strings.TrimSpace(name)))
}

func calculateCPUCores(cpuInfo []string) int {
	total := 0

	for _, info := range cpuInfo {
		info = strings.TrimSpace(info)
		if info == "" {
			continue
		}

		if matches := corePattern.FindStringSubmatch(info); len(matches) >= 2 {
			if count, err := strconv.Atoi(matches[1]); err == nil {
				total += count
				continue
			}
		}

		fields := strings.Fields(info)
		length := len(fields)
		if length < 2 {
			continue
		}
		if strings.EqualFold(fields[length-1], "core") {
			if count, err := strconv.Atoi(fields[length-2]); err == nil {
				total += count
				continue
			}
			if length >= 3 {
				if count, err := strconv.Atoi(fields[length-3]); err == nil {
					total += count
					continue
				}
			}
		}

		for i := length - 1; i >= 0; i-- {
			if strings.EqualFold(fields[i], "core") {
				for j := i - 1; j >= 0; j-- {
					if count, err := strconv.Atoi(fields[j]); err == nil {
						total += count
						i = -1
						break
					}
				}
				if i == -1 {
					break
				}
			}
			if strings.Contains(strings.ToLower(fields[i]), "core") {
				digits := corePattern.FindStringSubmatch(fields[i])
				if len(digits) >= 2 {
					if count, err := strconv.Atoi(digits[1]); err == nil {
						total += count
						break
					}
				}
			}
			if count, err := strconv.Atoi(fields[i]); err == nil {
				total += count
				continue
			}
		}
	}
	return total
}

func calculateMemoryInGB(memBytes uint64) int {
	if memBytes == 0 {
		return 0
	}
	memGB := int(math.Ceil(float64(memBytes) / float64(1<<30)))
	if memGB == 0 && memBytes > 0 {
		return 1
	}
	return memGB
}

func extractIPSegment(ip model.IP) string {
	if seg := firstIPv4Segment(ip.IPv4Addr); seg != "" {
		return seg
	}
	if seg := firstIPv6Segment(ip.IPv6Addr); seg != "" {
		return seg
	}
	joined := strings.TrimSpace(ip.Join())
	if seg := firstIPv4Segment(joined); seg != "" {
		return seg
	}
	if seg := firstIPv6Segment(joined); seg != "" {
		return seg
	}
	return ""
}

func firstIPv4Segment(input string) string {
	if input = sanitizeRawIP(input); input == "" {
		return ""
	}
	if ip := net.ParseIP(input); ip != nil {
		if v4 := ip.To4(); v4 != nil {
			return strconv.Itoa(int(v4[0]))
		}
	}
	if idx := strings.Index(input, "."); idx > 0 {
		return input[:idx]
	}
	return ""
}

func firstIPv6Segment(input string) string {
	if input = sanitizeRawIP(input); input == "" {
		return ""
	}
	lowered := strings.ToLower(input)
	if strings.HasPrefix(lowered, "::ffff:") {
		if seg := firstIPv4Segment(input[len("::ffff:"):]); seg != "" {
			return seg
		}
	}
	if idx := strings.Index(input, ":"); idx > 0 {
		return strings.ToUpper(input[:idx])
	}
	if ip := net.ParseIP(input); ip != nil && ip.To16() != nil {
		parts := strings.SplitN(strings.ToUpper(input), ":", 2)
		return parts[0]
	}
	return ""
}

func sanitizeRawIP(raw string) string {
	raw = strings.TrimSpace(raw)
	raw = strings.TrimPrefix(raw, "ip:")
	raw = strings.TrimPrefix(raw, "IP:")
	raw = strings.Trim(raw, "[]")
	if idx := strings.Index(raw, "%"); idx >= 0 {
		raw = raw[:idx]
	}
	return raw
}
